# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "/jekyll-cayman-theme"
paginate:     1

# About/contact
author:
  name:       Myungjun Cha
  url:        "http://myungjuncha.github.io"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman
